site_name: New Text Corpus

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - tags

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

nav:
  - index.md
  - whatwedo.md

  # - Section:
  #   - section/index.md
  #   - Page 1: section/page-1.md
  #   ...
  #   - Page n: section/page-n.md
