site_name: New Text Corp

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections

plugins:
  - tags

nav:
  - index.md
  - whatwedo.md

  # - Section:
  #   - section/index.md
  #   - Page 1: section/page-1.md
  #   ...
  #   - Page n: section/page-n.md
